DATASET: DanceTrack
SPLIT: test

PARAMS:
  delta_t: [1, 5, 10, 15, 20, 30, 5]
  conf_thr:
    low: .1
    high: .6
  ConsistentCamera:
    enable: True
    thr: .8
    tau: 100
  ConsistentMotion: True
  interpolation: False
  predictor:
    predictor: Kalman
    delta_t: 5
    preserve_scale: False
  motion_matching:
    mode: cons_hm_iou
    thr: .2
    cons_w: 64
    cons_tau: .2
    cons_score: .6
  iou_matching:
    mode: cons_hm_iou
    thr: .2
    cons_w: 64
    cons_tau: .2
    cons_score: .6
  post_trk:
    min_len: 10
    merge: null
    smooth: False
