DATASET: KITTI
SPLIT: test

PARAMS:
  delta_t: [1, 2, 3, 4, 5, 7, 30, 5]
  conf_thr:
    low: .0
    high: .0
  ConsistentCamera:
    enable: True
    thr: .7
    tau: 1000
  ConsistentMotion: True
  interpolation: True
  predictor:
    predictor: Linear
    delta_t: 5
    preserve_scale: True
  motion_matching:
    mode: cons_iou
    thr: .2
    cons_w: 32
    cons_tau: .2
    cons_score: .0
  iou_matching:
    mode: cons_iou
    thr: .2
    cons_w: 128
    cons_tau: .2
    cons_score: .0
  post_trk:
    min_len: 10
    merge:
      mode: iou
      thr: .5
    smooth: False
