DATASET: VisDrone
SPLIT: val

PARAMS:
  delta_t: [1, 3, 5, 7, 9, 5]
  conf_thr:
    low: .1
    high: .6
  nms_thr: .7
  ConsistentCamera:
    enable: True
    thr: 1.
    tau: null
  ConsistentMotion: True
  interpolation: False
  predictor:
    predictor: Kalman
    delta_t: 5
    preserve_scale: False
  motion_matching:
    mode: cons_iou
    thr: .2
    cons_w: 32
    cons_tau: .2
    cons_score: .0
  iou_matching:
    mode: cons_iou
    thr: .2
    cons_w: 32
    cons_tau: .2
    cons_score: .0
  post_trk:
    min_len: 10
    merge: null
    smooth: False